# przygotowanie do szukania
FIND_INIT(PREREQUISITES prerequisites)
unset(PREREQUISITES_INCLUDE_DIR CACHE)

# szukanie
if (CMAKE_HOST_WIN32)
	# szukamy biblioteki
	FIND_MODULE(PREREQUISITES_LIBPNG FALSE "libpng<?,15>" )
	FIND_MODULE(PREREQUISITES_LIBTIFF FALSE "libtiff" )
	FIND_MODULE(PREREQUISITES_SSLEAY32 FALSE "ssleay32" )
	FIND_MODULE(PREREQUISITES_LIBEAY32 FALSE "libeay32" )
	FIND_MODULE(PREREQUISITES_GLUT32 FALSE "glut32" )
	FIND_MODULE(PREREQUISITES_GIFLIB FALSE "giflib<?,4>" )
else()
	# uzywamy wbudowanego modułu wyszukiwania
	FIND_MODULE(PREREQUISITES_LIBPNG TRUE "libpng<?,15>" )
	FIND_MODULE(PREREQUISITES_LIBPNG TRUE "libpng<?,15>" )
	FIND_MODULE(PREREQUISITES_LIBTIFF TRUE "libtiff" )
	FIND_MODULE(PREREQUISITES_SSLEAY32 TRUE "ssleay32" )
	FIND_MODULE(PREREQUISITES_LIBEAY32 TRUE "libeay32" )
	FIND_MODULE(PREREQUISITES_GLUT32 TRUE "glut32" )
	FIND_MODULE(PREREQUISITES_GIFLIB TRUE "giflib<?,4>" )
endif()

# skopiowanie
FIND_FINISH(PREREQUISITES)
