#include <core/Plugin.h>
#include <plugins/c3d/C3DChannels.h>
#include "C3DParser.h"

CORE_PLUGIN_BEGIN("c3d", UID::GenerateUniqueID("{15AC5928-AAE3-4AB3-BFDB-447D4171A4E5}"))
	CORE_PLUGIN_ADD_PARSER(C3DParser);
	CORE_PLUGIN_ADD_OBJECT_WRAPPER(ScalarChannel);
	CORE_PLUGIN_ADD_OBJECT_WRAPPER(C3DAnalogChannel);
	CORE_PLUGIN_ADD_OBJECT_WRAPPER(EMGChannel);
	CORE_PLUGIN_ADD_OBJECT_WRAPPER(GRFChannel);
	CORE_PLUGIN_ADD_OBJECT_WRAPPER(MarkerChannel);
	CORE_PLUGIN_ADD_OBJECT_WRAPPER(MarkerSet);
CORE_PLUGIN_END