# przygotowanie do szukania
FIND_INIT(CURL curl)


# szukanie
FIND_SHARED(CURL_LIBCURL "libcurl" "libcurl")
if (CMAKE_HOST_WIN32)
	FIND_MODULE(CURL_LIBEAY32 FALSE "libeay32")
	FIND_MODULE(CURL_SSLEAY32 FALSE "libsasl")
	FIND_MODULE(CURL_LIBSASL FALSE "openldap")
	FIND_MODULE(CURL_OPENLDAP FALSE "ssleay32")
else()
	FIND_MODULE(CURL_LIBEAY32 TRUE "libeay32")
	FIND_MODULE(CURL_SSLEAY32 TRUE "libsasl")
	FIND_MODULE(CURL_LIBSASL TRUE "openldap")
	FIND_MODULE(CURL_OPENLDAP TRUE "ssleay32")
endif()

# skopiowanie
FIND_FINISH(CURL)

# sprawdzenie
if (CURL_LIBCURL_FOUND AND
	CURL_LIBEAY32_FOUND AND
	CURL_SSLEAY32_FOUND AND
	CURL_LIBSASL_FOUND AND
	CURL_OPENLDAP_FOUND)
	set(CURL_FOUND 1)
endif()
