find_package(PythonLibs)
if (${PYTHONLIBS_FOUND})
	set(LIBRARY_PYTHON_FOUND 1)
	set(PYTHON_LIBRARY_RELEASE ${PYTHON_LIBRARY} CACHE PATH "sciezka")
	# czy uda³o siê znaleŸæ odpowiednie warianty?
		if ( PYTHON_LIBRARY_DEBUG AND PYTHON_LIBRARY_RELEASE )
			set(LIBRARY_PYTHON_LIBRARIES optimized ${PYTHON_LIBRARY_RELEASE} debug ${PYTHON_LIBRARY_DEBUG})
			list(APPEND FIND_ALL_RELEASE_FILES PYTHON_LIBRARY_RELEASE)
			list(APPEND FIND_ALL_DEBUG_FILES PYTHON_LIBRARY_DEBUG)
		elseif ( PYTHON_LIBRARY_DEBUG )
			set(PYTHON ${PYTHON_LIBRARY_DEBUG})
			list(APPEND FIND_ALL_DEBUG_FILES ${PYTHON_LIBRARY_DEBUG})
			FIND_MESSAGE("Release version of PYTHON not found, using Debug version.")
		else()
			set(PYTHON ${PYTHON_LIBRARY_RELEASE} CACHE INTERNAL "")
			list(APPEND FIND_ALL_RELEASE_FILES ${PYTHON_LIBRARY_RELEASE})
			FIND_MESSAGE("Debug version of PYTHON not found, using Release version.")
		endif()
		set(PYTHON_LIBRARIES PYTHON)
else()
	message("pyton nie znaleziony!")
endif()
